#!/usr/bin/env bash
# This is a bash script that transfers a file from our client to a server
# Requirements:
#  The Path to the file to be tranferred
#  The IP of the server we want to transfer the file to
#  The username scp connects with
#  The path to the SSH private key that scp uses

if (($# < 3)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
        scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/; 
fi
