#!/usr/bin/env bash
# Install nginx web server
# Requirements
#       Install nginx on the web-01 server
#       Nginx should be listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
