#!/usr/bin/env bash
# Install nginx web server
# Requirements
#       Install nginx on the web-01 server
#       Nginx should be listening on port 80
#       /redirect_me should redirect to another page
#       redirection must be a "301 Moved permanently"
redirect="\\\trewrite ^/redirect_me(/*) https://www.google.com permanent;"
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "51i $redirect" /etc/nginx/sites-available/default #add at line 51
sudo service nginx start
