#!/usr/bin/env bash
# This script install and configure HAproxy on the server
# Requirement
#       Configure HAproxy so that it send traffix to web-01 and web-02
#       Algorithm: roundrobin algorithm
sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6\* -y
config="\\\nfrontend haproxy-main\n\tbind *:80\n\tmode http\n\tdefault_backend nginx_webservers\n\nbackend nginx_webservers\n\tbalance roundrobin\n\tserver web-01 100.26.225.121:80 check\n\tserver web-02   54.157.189.58:80 check\n"
sudo sed -i "19i $config" /etc/haproxy/haproxy.cfg # add to line 19
