#!/usr/bin/env bash
# Modify the nginx config to allow the server to work on port 80
sudo sed -i "s/8080/80/3" ~/etc/nginx/sites-enabled/default
sudo sed -i "s/ipv6only=yes//1" ~/etc/nginx/sites-enabled/default

