#!/usr/bin/env bash
# Modify the nginx config to allow the server to work on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
