#!/usr/bin/env bash
# script was used to debug a webserver to allow nginx serve a site on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep nginx | head -1)"
