#!/usr/bin/env bash
# The script displays a list of currently running processes
# It show all processes, for all users, including those which might not have a TTY
# It also show processes in a user-oriented format and process hierarchy
ps -axu
