#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# then prints hi on 9th iteration

i=0;
while ((i < 10)); do
	echo "Best School";
	if ((i == 8)); then
		echo "Hi";
	fi
	((i++));
done
