#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# then display hours from 0 to 12
# then display minutes from 1 to 59

min=1;
hour=0
echo "Hour:" "$hour";
while [ $min -lt 60 ] && [ $hour -lt 13 ]; do
	echo $min;
	((min++));
	if [ $min -eq 60 ] && [ $hour -ne 12 ]; then
		((hour++));
		echo "Hour:" "$hour";
		((min=1));
	fi
done
