#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
	 
ls | grep -Eo '\-(\w+\.?\w+)' | cut -c 2- > list
cat list
