#!/usr/bin/env bash
# This script gives you information about the school file.

# The Bash script check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

# -e flags checks if file exits
if [ -e "school" ]; then
	echo "school file exits";
	# -s flags checks if file is empty
	if [ ! -s "school" ]; then
		echo "school file is empty";
		else
			echo "school file is not empty";
	fi
	# -f flags checks for regular file
	if [ -f "school" ]; then
			echo "school is a regular file";
	fi

	else
		echo "school file does not exits";
fi
