#!/usr/bin/env bash
# This script installs a firewall if not installed.
# It setup some rules for the behavior of the uncomplicated firewall (ufw)
# The script assign some rules to ufw that allow the incoming traffic from the following:
#	22 (SSH)
#	443 (HTTPS SSL)
#	80 (HTTP)
#	it also redirects port 8080/TCP to port 80/TCP
# then it blocks all incoming traffic apart from the ones above.
sudo apt-get update -y 
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

command="\\\n*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT"

sudo sed -i "10i $command" /etc/ufw/before.rules #add at line 10


