#!/usr/bin/env bash
# This script modifies the client configuration file
# Requirements
#   SSH client configuration must use the private key ~/.ssh/school
#   SSH client configuration must refuse to authenticate using a password
Host 100.26.225.121
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
